GET http://localhost:3000/users

###

GET http://localhost:3000/users/609a4673c3d9a824f85deb05
###

POST http://localhost:3000/users
Content-Type: application/json

{
        "name": "amazing people",
        "age": 12
}

###

DELETE http://localhost:3000/users/609a402354c50512fc385827